version: '3.1'

services:

  go_api:
    restart: always
    container_name: go_api
    build:
      context: .
    command: /bin/sh -c "go run main.go"
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - DBEVENT=seeder
    networks:
      - local

  db:
    image: mysql:latest
    restart: always
    container_name: db_mysql
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    command: bash -c "mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci && go run /configs/seeder/seeder.go"
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      TZ: 'Asia/Jakarta'
    volumes:
        - ./mysql/data/sql_data/:/docker-entrypoint-initdb.d
        - ./mysql/data/conf.d/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
        - ./mysql-exporter/.my.cnf:/root/.my.cnf
        - db_data:/var/lib/mysql
        - ./configs:/configs/seeder
    ports:
      - 3306:3306
    networks:
      - local

  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:7.13.3'
    container_name: elasticsearch_09aseprayana09
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data


volumes:
    db_data:
    esdata:
      driver: local
networks:
  local:
    driver: bridge
